apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql-deployment
  labels: 
    app: mysql
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector: 
    matchLabels: 
      app: mysql
  template:
    metadata:
      name: mysql-db
      labels:
        app: mysql
    spec:
      containers:
       - name: mysql-pod
         image: mysql
         ports:
          - containerPort: 3306
         env: 
          - name: MYSQL_DATABASE
            value: wordpress-db
          - name: MYSQL_USER
            value: frazer
          - name: MYSQL_PASSWORD
            value: frazer
          - name: MYSQL_ROOT_PASSWORD
            value: password
#lien du volume à utiliser pour cet hote
         volumeMounts:
          - mountPath: /var/lib/mysql
            name: db-volume
#creation du volume        
      volumes:
        - name: db-volume
          hostPath:
            path: /db-data
            type: Directory
