apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wordpress-deployment
  labels: 
    app: wordpress
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector: 
    matchLabels: 
      app: wordpress
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
       - name: wordpress-pod
         image: wordpress
         ports:
          - containerPort: 80
         env: 
          - name: WORDPRESS_DB_HOST
            value: mysql-svc:8085
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_pwd
          - name: WORDPRESS_DB_NAME
            value: wordpress-db
  #lien du volume à utiliser pour cet hote
         volumeMounts:
          - mountPath: /var/www/html
            name: data-volume
  #creation du volume        
      volumes:
        - name: data-volume
          hostPath:
            path: /data
            type: Directory
