apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql
  name: wp-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-retain
  # volumeMode: Filesystem
  # volumeName: wp-pv